"""add_output_type_to_apps
Revision ID: 3578a7d17112
Revises: add_image_generation_models
Create Date: 2025-09-21 14:17:22.155620
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision = '3578a7d17112'
down_revision = 'add_image_generation_models'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns with defaults first, then remove the defaults
    op.add_column('app_runs', sa.Column('output_type', sa.String(), nullable=False, server_default='text'))
    op.add_column('app_runs', sa.Column('output_image_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'app_runs', 'files', ['output_image_id'], ['id'], ondelete='SET NULL')
    op.add_column('apps', sa.Column('output_type', sa.String(), nullable=False, server_default='text'))
    op.add_column('apps', sa.Column('image_generation_model_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'apps', 'image_generation_models', ['image_generation_model_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('security_classifications_name_tenant_id_key', 'security_classifications', type_='unique')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('security_classifications_name_tenant_id_key', 'security_classifications', ['name', 'tenant_id'])
    op.drop_constraint(None, 'apps', type_='foreignkey')
    op.drop_column('apps', 'image_generation_model_id')
    op.drop_column('apps', 'output_type')
    op.drop_constraint(None, 'app_runs', type_='foreignkey')
    op.drop_column('app_runs', 'output_image_id')
    op.drop_column('app_runs', 'output_type')
    # ### end Alembic commands ###